import sqlite3
import os

# Configuration
DB_PATH = "./data.db"
OUTPUT_FILE = "postgres_data_dump.sql"

# Tables to export (in order of dependency if any)
TABLES = [
    "partners",
    "products",
    "inbound_records",
    "outbound_records",
    "product_prices",
    "receivable_payments",
    "payable_payments"
]

def escape_string(val):
    if val is None:
        return "NULL"
    # Postgres uses single quotes for strings and escapes single quotes by doubling them
    return "'" + str(val).replace("'", "''") + "'"

def main():
    if not os.path.exists(DB_PATH):
        print(f"Error: Database file not found at {DB_PATH}")
        return

    print(f"Reading from {DB_PATH}...")
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("-- PostgreSQL Data Dump from SQLite\n")
        f.write("-- Generated by tradeflow migration script\n\n")
        f.write("BEGIN;\n\n")

        for table in TABLES:
            print(f"Exporting table: {table}")
            try:
                cursor.execute(f"SELECT * FROM {table}")
                rows = cursor.fetchall()
                
                if not rows:
                    continue

                # Get column names
                column_names = [description[0] for description in cursor.description]
                cols_str = ", ".join(f'"{c}"' for c in column_names) # Quote column names for safety

                f.write(f"-- Data for {table}\n")
                
                for row in rows:
                    values = []
                    for val in row:
                        if isinstance(val, (int, float)):
                            values.append(str(val))
                        elif val is None:
                            values.append("NULL")
                        else:
                            # Assume everything else is strict/text
                            values.append(escape_string(val))
                    
                    vals_str = ", ".join(values)
                    f.write(f"INSERT INTO {table} ({cols_str}) VALUES ({vals_str});\n")
                
                f.write("\n")
            except sqlite3.OperationalError as e:
                print(f"Skipping table {table} (not found in sqlite): {e}")

        f.write("COMMIT;\n")

    conn.close()
    print(f"Done! Data exported to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
